export const textStyles = {
  tinyRegular: {
    fontFamily: "Inter",
    fontSize: 12,
    fontWeight: 400,
    lineHeight: 14,
  },
  tinyEmphasis: {
    fontFamily: "Inter",
    fontSize: 12,
    fontWeight: 500,
    lineHeight: 14,
  },
  labelRegular: {
    fontFamily: "Inter",
    fontSize: 15,
    fontWeight: 400,
    lineHeight: 18,
  },
  smallRegular: {
    fontFamily: "Inter",
    fontSize: 13,
    fontWeight: 400,
    lineHeight: 16,
  },
  smallEmphasis: {
    fontFamily: "Inter",
    fontSize: 13,
    fontWeight: 500,
    lineHeight: 16,
  },
  labelEmphasis: {
    fontFamily: "Inter",
    fontSize: 15,
    fontWeight: 500,
    lineHeight: 18,
  },
  tableHeaderRegular: {
    fontFamily: "Inter",
    fontSize: 15,
    fontWeight: 500,
    lineHeight: 18,
  },
  tableHeaderEmphasis: {
    fontFamily: "Inter",
    fontSize: 15,
    fontWeight: 600,
    lineHeight: 18,
  },
  paragraphEmphasis: {
    fontFamily: "Inter",
    fontSize: 16,
    fontWeight: 600,
    lineHeight: 24,
  },
  headlineRegular: {
    fontFamily: "Inter",
    fontSize: 18,
    fontWeight: 500,
    lineHeight: 24,
  },
  paragraphRegular: {
    fontFamily: "Inter",
    fontSize: 16,
    fontWeight: 400,
    lineHeight: 24,
  },
  headlineEmphasis: {
    fontFamily: "Inter",
    fontSize: 18,
    fontWeight: 600,
    lineHeight: 24,
  },
  fieldsetHeaderRegular: {
    fontFamily: "Inter",
    fontSize: 18,
    fontWeight: 400,
    lineHeight: 24,
  },
  fieldsetHeaderEmphasis: {
    fontFamily: "Inter",
    fontSize: 18,
    fontWeight: 500,
    lineHeight: 24,
  },
  pageHeaderEmphasis: {
    fontFamily: "Inter",
    fontSize: 24,
    fontWeight: 600,
    lineHeight: 36,
    letterSpacing: -1,
  },
  subtitleRegular: {
    fontFamily: "Inter",
    fontSize: 20,
    fontWeight: 400,
    lineHeight: 32,
    letterSpacing: -1,
  },
  pageHeaderRegular: {
    fontFamily: "Inter",
    fontSize: 24,
    fontWeight: 500,
    lineHeight: 36,
    letterSpacing: -1,
  },
  subtitleEmphasis: {
    fontFamily: "Inter",
    fontSize: 20,
    fontWeight: 600,
    lineHeight: 32,
    letterSpacing: -1,
  },
  mediumValueEmphasis: {
    fontFamily: "Inter",
    fontSize: 26,
    fontWeight: 400,
    lineHeight: 36,
    letterSpacing: -1,
  },
  mediumValueRegular: {
    fontFamily: "Inter",
    fontSize: 26,
    fontWeight: 300,
    lineHeight: 36,
    letterSpacing: -1,
  },
  largeValueEmphasis: {
    fontFamily: "Inter",
    fontSize: 40,
    fontWeight: 400,
    lineHeight: 64,
    letterSpacing: -1,
  },
  largeValueRegular: {
    fontFamily: "Inter",
    fontSize: 40,
    fontWeight: 300,
    lineHeight: 64,
    letterSpacing: -1,
  },
};
